#!/bin/bash
# 創建簡單的藍色方塊圖標（使用 base64 編碼的最小 PNG）

# 16x16 藍色 PNG (base64)
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAEklEQVR42mNgGAWjYBSMAggAAQQAAU3Z8gwAAAAASUVORK5CYII=" | base64 -d > icon16.png

# 48x48 藍色 PNG (base64)
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAARklEQVR42mNgGAWjYBSMglEwCkbBKBgFo2AUjIJRMApGwSgYBaNgFIyCUTAKRsEoGAWjYBSMglEwCkbBKBgFo2BwAwABBAABw8j8ogAAAABJRU5ErkJggg==" | base64 -d > icon48.png

# 128x128 藍色 PNG (base64)
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAaklEQVR42u3RAQ0AAAgDIN8/9K3hDFpAayIgIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi8mfABdoJAAGe1FgaAAAAAElFTkSuQmCC" | base64 -d > icon128.png

echo "Icons created!"
ls -lh
